"""cliente cpf nullable

Revision ID: 081cc21873fe
Revises: 67b77c745e83
Create Date: 2026-09-25 20:27:26.550065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '081cc21873fe'
down_revision: Union[str, None] = '67b77c745e83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cliente', 'cpf',
               existing_type=sa.VARCHAR(length=14),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cliente', 'cpf',
               existing_type=sa.VARCHAR(length=14),
               nullable=False)
    # ### end Alembic commands ###
