"""
Revision ID: 67b77c745e83
Revises: 
Create Date: 2026-09-25 14:51:35.225648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '67b77c745e83'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('usuario_email_key', 'usuario', type_='unique')
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.create_unique_constraint('usuario_email_key', 'usuario', ['email'])
    # ### end Alembic commands ###
