"""plano dias_semana array

Revision ID: e0851272df78
Revises: 081cc21873fe
Create Date: 2026-10-08 14:00:28.638633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e0851272df78'
down_revision: Union[str, None] = '081cc21873fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plano', sa.Column('dias_semana', postgresql.ARRAY(sa.SmallInteger()), nullable=False))
    op.drop_column('plano', 'dia_semana')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plano', sa.Column('dia_semana', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('plano', 'dias_semana')
    # ### end Alembic commands ###
